
name: Caching Mercurial repo

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Setup Mercurial
      run: |
        python3 -m pip install hg-evolve --user
        echo "[extensions]" >> ~/.hgrc
        echo "topic =" >> ~/.hgrc
        hg version -v

    - name: Setup cached Mercurial repo
      uses: actions/cache@v4
      with:
        path: mercurial-devel
        key: cached-repo-${{ github.run_id }}
        restore-keys: |
          cached-repo

    - name: Clone or update Mercurial repo
      run: |
        if [ -d mercurial-devel ]; then
            echo "Directory exists. Pull."
            hg pull --cwd mercurial-devel
            hg up default
        else
            echo "Directory does not exist. Clone."
            hg clone https://foss.heptapod.net/mercurial/mercurial-devel
        fi

    - name: Use Mercurial repo
      run: |
        cd mercurial-devel
        hg log -r "-12:"
