name: Test Mercurial from sources on Ubuntu

on: push

env:
  HGWITHRUSTEXT: cpython

jobs:

  update-repo:
    runs-on: ubuntu-latest

    steps:

      - name: Setup Mercurial app
        run: |
          python3 -m pip install hg-evolve --user
          echo "[extensions]" >> ~/.hgrc
          echo "topic =" >> ~/.hgrc
          hg version -v

      - name: Setup cached Mercurial repo
        uses: actions/cache@v4
        with:
          path: ~/mercurial-devel
          key: cached-repo-${{ github.run_id }}
          restore-keys: |
            cached-repo

      - name: Clone or update Mercurial repo
        run: |
          if [ -d ~/mercurial-devel ]; then
              echo "Directory exists. Pull."
              hg pull --cwd ~/mercurial-devel
          else
              echo "Directory does not exist. Clone."
              hg clone https://foss.heptapod.net/mercurial/mercurial-devel ~/mercurial-devel
          fi
          hg up default --cwd ~/mercurial-devel

      - name: Check Mercurial repo
        run: |
          cd ~/mercurial-devel
          hg log -r "-4:"
          hg sum

  tests:
    needs: update-repo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: checks
            runtest_args: "--time --test-list /tmp/check-tests.txt"

          - name: rust-cargo-test

          - name: test-c
            runtest_args: "--no-rust --blacklist /tmp/check-tests.txt"

          - name: test-pure
            runtest_args: "--pure --blacklist /tmp/check-tests.txt"

          - name: test-rust
            runtest_args: "--rust --blacklist /tmp/check-tests.txt"

          - name: test-rust-rhg
            runtest_args: "--rust --rhg --blacklist /tmp/check-tests.txt"

          - name: test-chg
            runtest_args: "--chg --blacklist /tmp/check-tests.txt"

    steps:
      - name: Setup cached Mercurial repo
        uses: actions/cache@v4
        with:
          path: ~/mercurial-devel
          key: cached-repo-${{ github.run_id }}
          restore-keys: |
            cached-repo

      - name: Check Mercurial repo
        run: |
          cd ~/mercurial-devel
          hg log -r "-4:"
          hg sum

      - name: Create check-tests.txt
        run: |
          cd ~/mercurial-devel
          ls -1 tests/test-check-*.* > /tmp/check-tests.txt
          cat /tmp/check-tests.txt

      - name: Install apt packages
        run: sudo apt-get install gettext git-lfs

      - if: contains(${{ matrix.name }}, 'rust')
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.79.0

      - if: matrix.name == 'rust-cargo-test'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.79.0
          components: clippy

      - if: matrix.name == 'checks'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.79.0
          components: rustfmt

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python packages
        run: python -m pip install setuptools docutils pytest-vcr black==23.3.0 pylint pyflakes pygments

      - if: matrix.name == 'rust-cargo-test'
        name: Run Rust tests
        run: |
          cd ~/mercurial-devel
          make rust-tests
          make cargo-clippy

      - if: matrix.name != 'rust-cargo-test'
        name: Run tests
        run: |
          echo "matrix.name: ${{ matrix.name }}"
          cd ~/mercurial-devel
          python tests/run-tests.py --color=always ${{ matrix.runtest_args }}
